### ISSUE TITLE
BackstopJS font rendering consistency

### ISSUE THREAD

**Issue by RRorg** [bitcrowd/bitstyles#258]
The font rendering seems to be highly dependent on the user's personal settings - see the difference in font rendering with LCD smoothing (left) and without:
<img width="608" alt="screenshot 2017-01-12 um 14 11 58" src="https://cloud.githubusercontent.com/assets/11065422/21892663/27f9ebd6-d8d8-11e6-8d1b-8d78b979dcea.png">

Changing the settings on my computer resolved the problem for the most part, but there are still minor differences:
![screenshot 2017-01-12 um 14 57 28](https://cloud.githubusercontent.com/assets/11065422/21892672/3a052a2a-d8d8-11e6-90ee-c91301561325.png)
![screenshot 2017-01-12 um 14 59 20](https://cloud.githubusercontent.com/assets/11065422/21892677/3dd11434-d8d8-11e6-8ddf-f166f6260cf7.png)

Darren and I made sure to use both the same versions of all dependencies, as well as the same font files (Helvetica).

**Comment by planktonic** [comment]
To investigate: any chance CSS `-webkit-font-smoothing` overrides the system setting?

**Comment by RRorg** [comment]
see this:

https://github.com/garris/BackstopJS/issues/361#issuecomment-266591166

**Comment by planktonic** [comment]
I didn't have any luck setting the webfont smoothing in an `onBefore` event as suggested in that thread, but setting it in css worked (on `html`, in `base/_typography.scss`) i.e. re-built the reference images with antialiasing set to `none`, then changing the system option on macOS for font-smoothing had no effect — tests passed when run with `npm run test`.

We don’t want this to be part of the css output of course, so maybe add this one-liner to `styleguide-extras.scss` and rebuild all the test images. Could be worth doing this as part of #256 as that changed a lot of reference images due to changed typography — it would minimise the repo size due to image rewriting.

**Comment by RRorg** [comment]
if minimizing repo size is a concern, let's run pngcrush or something similar over the reference file.
On a quick test, it loslessly crushed their size from 4.7MB to 3.2MB

**Comment by planktonic** [comment]
I meant more the fact that git stores the entire history of a file — changing large files often is expensive (also means crushing the reference images now will make the repo larger!).

**Comment by planktonic** [comment]
fixed by #256
